Ajout connexion
Master-Trolls-of-IT/PFEE-back pull request #2
Opened 2023-10-01 15:04 UTC by AkaMirai9

Création des routes :

- POST '/login' : Permettra à l'utilisateur de se connecter à l'aide de d'une requête de la forme {username, password}
- GET '/check-cookie': Permettra à l'utilisateur de savoir si son cookie est toujours valid et donc de savoir si on peux le log directement

2023-10-01 23:33 UTC, lesageduvillage requested changes

2023-10-01 23:33 UTC, lesageduvillage commented on src/middleware/passport-strategy.ts
> +        if (admin.password === password) {
stocké sans hash les mdp ? bizarre non ?

2023-10-01 23:33 UTC, lesageduvillage commented on src/middleware/verify-cookie.ts
> +    if (req.isAuthenticated() || req.path === '/login') next();
pk tu laisse le /login on pourrait hardcode l'url pour skip l'expiration nan ? pas très secure ou je capte pas un truc

2023-10-01 23:33 UTC, lesageduvillage commented on src/model/administrator.ts
> +    creationDate: string;
pas bon format creation date et last login

2023-10-01 23:33 UTC, lesageduvillage commented on src/service/types/administrator.ts
> +    creation_date: string;
pareil

2023-10-01 23:33 UTC, lesageduvillage commented on src/types.d.ts
> +        creationDate: string;
idem

2023-10-04 21:42 UTC, AymanImhah approved these changes

2023-10-04 22:37 UTC, lesageduvillage approved these changes

2023-10-04 22:57 UTC, merged